/**
 * Generated by `supabase gen types typescript --linked > src/types/database.ts`.
 * Placeholder until first migration. Run the generator to overwrite.
 */
export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};
